Runner: record more metrics
open-energy-transition/solver-benchmark pull request #45
Opened 2024-10-23 16:39 UTC by jacek-oet

2024-10-24 06:57 UTC, siddharth-krishna commented
Thanks Jacek! This is a good start. Some suggestions for next steps:

- [ ] Check if the code also works for other solvers (glpk, scip)?
- [ ] Add `max_integrality_violation` and `duality_gap` to `results` returned by `run_solver.py`
- [ ] What does linopy return for the above 2 metrics when the input file is not a MIP? If it is something sensible, then run this code on all our benchmarks. Otherwise, can we figure out a way to ask linopy / `run_benchmarks.py` whether each benchmark is an LP or MIP and only run the above code for MIPs?

2024-10-25 07:41 UTC, jacek-oet commented
The previous code only works for the HiGHS solver. Other solvers use a different method to retrieve those values.
I updated the code to get max_integrality_violation for all solvers. I am now checking how to retrieve the duality_gap for all solvers and I will run all benchmarks.

2024-10-25 08:07 UTC, siddharth-krishna commented on runner/run_solver.py
> +    primal_values = solver_result.solution.primal
Thanks! Please put a comment here that we are not using `solver_result.solver_model.getInfo()` because it works for Highs but not solver X

2024-10-28 07:57 UTC, jacek-oet commented
I added `max_integrality_violation` and `duality_gap` to the results returned by `run_solver.py` and am re-running the code on all our benchmarks. However, for GLPK, I can't get the `duality_gap` because, in Linopy, it only returns `status` and `solution` (`Result(status, solution)`). Other solvers return a model, which allows us to retrieve the `duality_gap` from it.

> For LP, if we use IPM, do we crossover to get a basic solution? What solution quality do we require? Vertex or optimal?

For linear programming (LP), if we use an interior point method (IPM), the process does not naturally yield a basic (vertex) solution because IPMs find points within the feasible region rather than at its vertices.

To obtain a basic (vertex) solution from an IPM, a crossover step is typically used. This step takes the approximate solution from the IPM and moves it to a basic feasible solution, ideally at a vertex of the feasible region. This is particularly useful in cases where a vertex (or extreme point) is required.

In summary, the solution quality primarily requires optimality and feasibility, but if a vertex solution is specifically needed, a crossover step is necessary.

2024-10-29 09:09 UTC, siddharth-krishna reviewed
Thanks, Jacek. We also need to add these new metrics to the website. For now, perhaps the simplest way to do this is to add a little table to the Benchmark details page, with columns "Solver, Max Integrality Violation, Duality Gap". You can display the results from the last iteration for each solver, if the results CSV has multiple iterations. Also, make sure you only display this info for Benchmarks that are MIPs, not for LPs. Thanks!

2024-10-30 08:17 UTC, jacek-oet commented
I added a new table for MIP Information (displayed only for MIP problems) on the benchmark detail page.
![image](https://github.com/user-attachments/assets/8fe5fbd1-04c5-4104-a45e-cd51f799a280)

Note: I assume pypsa-gas+wind+sol+ely-1h-ucgas and pypsa-gas+wind+sol+ely-1h are MIP problems, so I added mock data for them (Max Integrality Violation, Duality Gap).

2024-10-30 08:31 UTC, siddharth-krishna commented
Thanks Jacek. The table looks good. But I think we want to programmatically determine which benchmarks are MIPs. Can we use the `Technique:` line from `benchmarks/pypsa/metadata.yaml`?

Also, I don't see the code updating the website in the PR's diff. Did you not push it yet? Thanks

2024-10-30 08:57 UTC, jacek-oet commented
> Thanks Jacek. The table looks good. But I think we want to programmatically determine which benchmarks are MIPs. Can we use the `Technique:` line from `benchmarks/pypsa/metadata.yaml`?
> 
> Also, I don't see the code updating the website in the PR's diff. Did you not push it yet? Thanks

I will use the Technique field from metadata.yaml and add mock data accordingly

2024-10-31 13:36 UTC, siddharth-krishna requested changes
Would love a few small changes, thanks!

2024-10-31 13:36 UTC, siddharth-krishna commented on runner/run_solver.py
> +        Path(__file__).parent / "solution/{problem_file.stem}-{solver_name}.sol"
why not use `solution_dir` in the path here?

2024-10-31 13:36 UTC, siddharth-krishna commented on runner/run_solver.py
> +            # We are not using solver_result.solver_model.getInfo() because it works for HiGHS but not for other solvers.
Perhaps now this comment makes more sense to be put inside the `calculate_integrality_violation` function

2024-10-31 13:36 UTC, siddharth-krishna commented on website/benchmarks.py
> +            ].drop_duplicates()
Not sure if this would work? What if different iterations of a solver had different duality gaps for some reason? Perhaps better to drop duplicates by only considering the solver column, or to consider the last row for each solver?

2024-10-31 13:36 UTC, siddharth-krishna commented on runner/run_solver.py
> +        return info.mip_node_count >= 0
@jacek-oet what happens if the solver is GLPK?

2024-10-31 13:36 UTC, siddharth-krishna commented on runner/run_solver.py
> +        return info.mip_node_count >= 0
Perhaps a good idea in general to have a default case where it raises a NotImplementedError

2024-11-01 08:45 UTC, jacek-oet commented on runner/run_solver.py
> +        return info.mip_node_count >= 0
If we raise a NotImplementedError, we won’t be able to use GLPK because it will throw that error every time we try to use GLPK.

2024-11-01 08:48 UTC, siddharth-krishna commented on runner/run_solver.py
> +        return info.mip_node_count >= 0
Yes, but my point is that there is no `else:` block here, which is bad coding practice. Because then perhaps the code returns `None` in the case when `solver_name == "glpk"`? It is better to add an `elif solver_name == "glpk":` block to specify what happens for GLPK, and have `else: raise NotImplementedError` to remind ourselves to update this function when we add a new solver to the code.

2024-11-01 08:49 UTC, siddharth-krishna commented on runner/run_solver.py
> +        We are not using solver_result.solver_model.getInfo() because it works for HiGHS but not for other solve
```suggestion
        We are not using solver_result.solver_model.getInfo() because it works for HiGHS but not for other solvers
```

2024-11-07 08:11 UTC, siddharth-krishna approved these changes

2024-11-07 08:11 UTC, merged