Runner: run multiple versions of each solver
open-energy-transition/solver-benchmark pull request #55
Opened 2024-11-11 15:31 UTC by jacek-oet

2024-11-12 06:44 UTC, siddharth-krishna reviewed
Thank Jacek, it looks good overall, but I left some suggestions and requests. Also, let's make a separate PR to add a CI test for streamlit, especially if you switch from what you have here to something like https://docs.streamlit.io/develop/concepts/app-testing/automate-tests#running-the-app-tests

2024-11-12 06:44 UTC, siddharth-krishna commented on runner/run_benchmarks.py
> +        return ValueError(f"Package Not Found Error {solver_name}")
```suggestion
        elif solver_name == "glpk":
            return version("glpk")
        else:
            raise NotImplementedError(f"We do not yet support {solver_name}")
```

Again, it's better to explicitly raise an error like in my suggestion so that when we add a new solver we get a meaningful error. Also note that you `raise` an error, not `return` it.

2024-11-12 06:44 UTC, siddharth-krishna commented on runner/run_benchmarks.py
> +        mode = "a"
```suggestion
    mode = "w" if override else "a"
```

2024-11-12 06:44 UTC, siddharth-krishna commented on runner/run_benchmarks.py
> +        )
It's getting complex enough that perhaps in the next PR we should switch to using the `argparse` library?

2024-11-12 06:44 UTC, siddharth-krishna commented on runner/requirements-2020.txt
> +highspy==1.5.0.dev0
If a solver's first release was in e.g. 2022, then let's not include it in `requirements-2020.txt` and let's change `run_benchmarks.py` to only run the solvers that are present in the pip environment. You can query `linopy.available_solvers` to find out which ones are available.

2024-11-14 07:53 UTC, siddharth-krishna requested changes
Thanks, Jacek. A couple of more small things to be done before we can merge this. 🙏 

>  All pages of the website other than the Solver History page should only use the data for the latest version of each solver

Did you do this already? If not, please implement that as well, thanks.

2024-11-14 07:53 UTC, siddharth-krishna commented on results/benchmark_results.csv
> +pypsa-eur-sec-2-24h,highs,ok,optimal,15337522234.402815,52.85370707511902,431.176,,,,2024
Why is there no value for `Solver Version` for most lines?

2024-11-14 07:53 UTC, siddharth-krishna commented on runner/run_benchmarks.py
> +    mode = "w" if override else "a"
Why would I ever need to append CSV headers onto an existing file? You already have an if statement at the place where this function is called that only calls this function if overriding/writing a new file. So can't the mode in this function always be `w`?

2024-11-14 07:53 UTC, siddharth-krishna commented on runner/requirements-2022.txt
> +pypsa==0.31.1
Do we need `pypsa` for the runner? 🤔

2024-11-20 09:02 UTC, siddharth-krishna reviewed
Thanks, Jacek! I left 2 small suggestions, but this looks good otherwise. I presume you've tested it locally on the 2 sample LP files or the smallest benchmarks?

If you could quickly implement these suggestions, then I can run all the benchmarks on all the solver versions and update the results file in this PR before we merge it in. 🙏

2024-11-20 09:02 UTC, siddharth-krishna commented on runner/run_benchmarks.py
> +                solver_version = get_solver_version(solver)
Right now this is being called once for every benchmark. That could be slow if `conda list` takes some time. Can we make a `solver_versions` dict that maps each solver in `solvers` to its version before we start the `for file_info in benchmark_files_info:` loop? That way we only query each solver's version once.

2024-11-20 14:11 UTC, jacek-oet commented on runner/benchmark_all.sh
> +        pip install -r "$req_file"
As we have removed the requirements files, it is necessary to update the CI's 'Run sample benchmarks' step. I will create a separate PR to address this update.

2024-11-20 14:23 UTC, siddharth-krishna approved these changes

2024-11-20 14:23 UTC, siddharth-krishna commented on .github/workflows/ci.yaml
> -      - name: Run sample benchmarks
Why was this CI test removed?

2024-11-20 14:28 UTC, jacek-oet commented on .github/workflows/ci.yaml
> -      - name: Run sample benchmarks
@siddharth-krishna I commented about that here.
https://github.com/open-energy-transition/solver-benchmark/pull/55#discussion_r1850388500

2024-11-26 07:57 UTC, jacek-oet commented
@siddharth-krishna LGTM! (As author of this PR, I am not permission to approve.)

2024-11-26 08:13 UTC, merged